import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import { Inter } from 'next/font/google';
import { CategoriesProvider } from './context/CategoryContext';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Quiz Master',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.theme;
                  if (
                    theme === 'dark' ||
                    (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches)
                  ) {
                    document.documentElement.classList.add('dark');
                  } else {
                    document.documentElement.classList.remove('dark');
                  }
                } catch (_) {}
              })();
            `,
          }}
        />
      </head>

      <body className={`${inter.variable}`}>
        <div className='min-h-screen bg-gray-50 dark:bg-gray-800 transition-colors duration-300 flex flex-col'>
          <Header />
          <CategoriesProvider>
            <main className='flex-grow flex flex-col items-center justify-center p-4 dark:bg-[url(/images/dark-background.jpeg)] bg-[url(/images/background.png)] bg-cover bg-center text-gray-900 dark:text-gray-100'>
              {children}
            </main>
          </CategoriesProvider>
        </div>
      </body>
    </html>
  );
}
